version: '3.1'

volumes:
  db:

services:
  mediawiki:
    image: semanticmw:latest
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - /var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      wgServer: http://testwiki:8080
      wgSecretKey: 5fcb0b0d254322d84d2c38f81bd6b1bcacbce59436e0c370d02e0695320a2eee
      wgUpgradeKey: 7222a486ba79059b
      domainName: testwiki.local
  database:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
