# Add this to end of your autogenerated LocalSettings.php

# Good artists copy; great artists steal - wirehead/semantic-mediawiki-docker
# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
#wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'WikiEditor' );


# End of automatically generated settings.
# Add more configuration options below.

# Load our extensions

#wfLoadExtension( 'GraphViz' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'JsonConfig' );
wfLoadExtension( 'Graph' );
#wfLoadExtension( 'SubPageList3' );
#wfLoadExtension( 'Scribunto' );
#wfLoadExtension( 'SemanticScribunto' );
wfLoadExtension( 'TemplateStyles' );

$wgScribuntoDefaultEngine = 'luastandalone'; # tbh IDK what this does but I stole it anyways



# End of automatically generated settings.
# Add more configuration options below.
enableSemantics( 'testwiki.local' );
#$wgVectorResponsive = true;